# Generated by Django 2.2.12 on 2020-07-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200702_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='unti_price',
            new_name='unit_price',
        ),
    ]
