# Generated by Django 2.2.12 on 2020-07-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200702_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='name',
        ),
        migrations.AddField(
            model_name='option',
            name='bottle_size',
            field=models.CharField(choices=[('250', '250 ML'), ('750', '750 ML')], default='250', max_length=1),
        ),
    ]
