# Generated by Django 2.2.12 on 2020-07-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200703_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bottom_price',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
