# Generated by Django 2.2.12 on 2020-07-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_cart_cim_item_oim_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
