# Generated by Django 2.2.12 on 2020-07-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cim',
            name='user',
        ),
        migrations.AddField(
            model_name='cim',
            name='cart',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Cart'),
            preserve_default=False,
        ),
    ]
