# Generated by Django 2.2.12 on 2020-07-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cim',
            name='total',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
