# Generated by Django 2.2.12 on 2020-07-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_cim_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cim',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
