# Generated by Django 2.2.12 on 2020-07-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200709_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cim',
            name='total',
        ),
    ]
