# Generated by Django 2.2.12 on 2020-07-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_cim_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
