# Generated by Django 2.2.12 on 2020-07-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_item_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
