# Generated by Django 2.2.12 on 2020-07-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200709_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total',
        ),
    ]
