# Generated by Django 2.2.12 on 2020-07-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cim',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
