# Generated by Django 2.2.12 on 2020-07-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Total_price',
            new_name='total_price',
        ),
    ]
