# Generated by Django 2.2.12 on 2020-07-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20200709_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_bill',
        ),
    ]
